### ISSUE TITLE
List values

### ISSUE THREAD

**Issue by harrysalmon** [genthalili/merkle-json#1]
Thanks for the library, very useful!

In the example 
```
obj = {
    'keyD': 1,
    'keyA': 2,
    'keyC': [4, 3],
    'keyB': 4,
}
```

And 

```
obj_unordered = {
    'keyC': [3, 4],
    'keyA': 2,
    'keyB': 4,
    'keyD': 1,
}
```

Hash equivalently and then as you say the objects aren't equivalent. Could you explain the desire for them to share a hash? It's not the behaviour that I naively expected.

**Comment by genthalili** [comment]
Hi @harrysalmon, 

> MerkleJson guarantees the unique hash, **regardless of the order of the json objects in a list**. Also it detects if an merkle hash already exists in the object which avoids re-calculations. Furthermore, you can keep the consistency of the object only partially, by ignoring other irrelevant keys.

The idea is to generate a unique hash, regardless of the position of it's value (no metter the type of the value in the list ..)
example : 

````py
obj = {
    'keyD': 1,
    'keyA': 2,
    'keyC': [ 2, { 'value':1 }, [1,2.3, {'val':2}]],
    'keyB': 4,
}

other_obj= {
    'keyC': [{ 'value':1 }, 2, [1,2.3, {'val':2}] ],
    'keyA': 2,
    'keyB': 4,
    'keyD': 1,
}
obj == other_obj # will return False / Python comparing dict

mj.hash(obj_unordered) == mj.hash(obj) # will return True / using merkle-json (this) module

# other example
assert mj.hash([1,2,3]) == mj.hash([3,1,2])
assert mj.hash([1,2,3]) == mj.hash([1,2,3])
assert [1,2,3] != [3,1,2]
assert [1,2,3] == [1,2,3]
````

**Comment by harrysalmon** [comment]
Hi @genthalili, understood, thanks very much for taking the time to answer!
